{
 "title": "Smart Pool",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Temperature Actuator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  signalVal\nFROM temperature_actuator\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Hydromassage Actuator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  power\nFROM hydromassage_actuator\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Presence Detection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  presence\nFROM presence_detection\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Chlorine Actuator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  signalVal\nFROM chlorine_actuator\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Chlorine Levels",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value\nFROM chlorine_levels\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Water Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value\nFROM water_temperature\nORDER BY timestamp"
    }
   ]
  },
  { "type": "welcome", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 48 } },
  { "type": "gettingstarted", "gridPos": { "h": 9, "w": 24, "x": 0, "y": 51 } },
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 15, "w": 12, "x": 0, "y": 60 } },
  { "title": "Latest from the blog", "type": "news", "gridPos": { "h": 15, "w": 12, "x": 12, "y": 60 } }
 ]
}